### ISSUE TITLE
My terraform script add a CDROM capacity 374 KiB to a VM, a bad subnet and the debian 11 karnel panic on first boot

### ISSUE THREAD

**Issue by ahumain** [nutanix/terraform-provider-nutanix#497]
# my terraform script add a CDROM capacity 374 KiB to a VM, a bad subnet and the debian 11 karnel panic on first boot

## global information
- prisme central: 2021.9.0.4
- Terraform: 1.2.9
- Nutanix provider: 1.7.0
- I have all rights on prism central

### Terraform code
```hcl
terraform {
  required_providers {
    nutanix = {
      source = "nutanix/nutanix"
      version = "1.7.0"
    }
  }
}

provider "nutanix" {
 username = "<my_username>"
 password = "<my_password>"
 endpoint = "<my_prism_central_endpoint>"
 insecure = true
}

variable "vmname" {
  type = string
  description = "Name of the VM to be created"
  default = "terraformtest01"
}

variable "cluster_name" {
  type = string
  default = "ca54a6fd-d038-4034-89ef-4021a05789fb"
}

variable "nb_socket" {
  type = number
  description = "Number of sockets. 1 socket = 1 CPU"
  default = 2
}

variable "nb_vcpu" {
  type = number
  description = "Number of vCPUs per socket. 1 vCPU = 1 core"
  default = 1
}

variable "nb_memory" {
  type = number
  description = "Number of memory in mib (MiB). The default value is 4000"
  default = 4096
}

variable "subnet" {
  type = string
  description = "Subnet of the VM"
  default = "fc483036-df06-433c-aaf8-3c373ac32cbc"
}

resource "nutanix_virtual_machine" "terraformtest01" {
  name = "var.vmname"
  description = "VM Created by Terraform with Nutanix Webapps"
  provider = nutanix
  cluster_uuid = var.cluster_name
  num_vcpus_per_socket = var.nb_vcpu
  num_sockets = var.nb_socket
  memory_size_mib = var.nb_memory

  nic_list {
    subnet_uuid  = var.subnet
  }

  disk_list {
    disk_size_mib = 20000
    data_source_reference = {
      kind = "image"
      uuid = "966ea167-fbca-4c5f-b86c-b466700e5e65"
    }
    storage_config {
      storage_container_reference {
        kind = "storage_container"
        uuid = "45da24e3-f2ab-4643-b244-8f5aa05b903f"
      }
    }
  }
  disk_list {
    disk_size_mib = 10000
  }
  guest_customization_cloud_init_user_data = base64encode(file("cloudinit.yml"))

}
```

### cloudinit.yml
```yaml
#cloud-config
hostname: terraformtest01
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    home: /home/debian
    shell: /bin/bash
    lock_passwd: false
    passwd: <my_password_hash>
ssh_pwauth: true
write_files:
  - path: /etc/network/interfaces.d/50-cloud-init
    content: |
      auto lo
      iface lo inet loopback
      auto ens3
      iface ens3 inet static
       address x.x.x.x
       gateway x.x.x.x
  
  - path: /etc/resolv.conf
    content: |
      nameserver x.x.x.x x.x.x.x

package_update: true
package_upgrade: true

swap:
  filename: /swap
  size: 4000000000
  maxsize: 4000000000
  
runcmd:
  - sudo systemctl restart networking.service
  - sudo reboot

```

## On nutanix
The VM is created but, one cdrom is added with capacity 374 KiB and the VM is in a bad subnet. I have give correct subnet uuid in the code. 

### Karnel panic on first boot
When the VM is created, the debian 11 kernel panic on first boot. I think the problem comes from the CDROM.

![karnel pannic](https://user-images.githubusercontent.com/28758850/192086626-5cd9ba71-ba7f-41ad-a4c2-43c1e0363a52.png)

After the reboot manually, the VM is not on karnel panic and the cloudinit.yml is executed.

Why the VM is created with a CDROM and a bad subnet ? And debian 11 karnel panic because of the CDROM ? It's a bug or I have made a mistake in my code ?
