### ISSUE TITLE
Example Doc - Ubuntu VM deployment with static IP

### ISSUE THREAD

**Issue by ktinthecloud** [nutanix/terraform-provider-nutanix#628]
Please provide a working example of deploying an Ubuntu VM with a static IP.  I've tried different combinations of passing metadata or userdata via `guest_customization_cloud_init_user_data` or `guest_customization_cloud_init_meta_data`, but nothing seems to work.

**Comment by davhdavh** [comment]
It took forever to figure this out...
```
power_state:
  delay: now
  mode: reboot
  message: Reboot after init
  timeout: 120
  condition: true

write_files:
- path: /etc/netplan/50-cloud-init.yaml
  permissions: '0600'
  content: |
    network:
      version: 2
      ethernets:
        e:
          match:
            name: e*
          set-name: ens3
          addresses:
          - 192.168.229.${100+count.index}/24
          routes:
          - to: default
            via: 192.168.229.1
          nameservers:
            search: [xxx]
            addresses:
            %{ for s in data.nutanix_clusters.clusters.entities.0.name_server_ip_list ~}
            - ${s}
            %{ endfor ~}
```

I still haven't figured out, how to give it the right ip without a reboot
